version: "3.9"

services:
  planka:
    image: navystack/planka:latest
    restart: unless-stopped
    volumes:
      - user-avatars:/app/public/user-avatars
      - project-background-images:/app/public/project-background-images
      - attachments:/app/private/attachments
      - ./etc/TLS/DigiCertGlobalRootCA.crt.pem:/app/public/DigiCertGlobalRootCA.crt.pem
    ports:
      - 3000:1337
    environment:
      - BASE_URL=http://localhost:3000
      - DATABASE_URL=postgresql://postgres@my-server.postgres.database.azure.com/planka?ssl=true&sslmode=require&sslrootcert=/app/public/DigiCertGlobalRootCA.crt.pem
      - SECRET_KEY=notsecretkey
      - TRUST_PROXY=0

      # - TOKEN_EXPIRES_IN=365 # In days
      # related: https://github.com/knex/knex/issues/2354
      # As knex does not pass query parameters from the connection string we
      # have to use environment variables in order to pass the desired values, e.g.
      # - PGSSLMODE=<value>

      # Configure knex to accept SSL certificates
      # - KNEX_REJECT_UNAUTHORIZED_SSL_CERTIFICATE=false

      # - DEFAULT_ADMIN_EMAIL=demo@demo.demo # Do not remove if you want to prevent this user from being edited/deleted
      # - DEFAULT_ADMIN_PASSWORD=demo
      # - DEFAULT_ADMIN_NAME=Demo
      # - DEFAULT_ADMIN_USERNAME=demo

      # - OIDC_ISSUER=
      # - OIDC_CLIENT_ID=
      # - OIDC_CLIENT_SECRET=
      # - OIDC_SCOPES=openid email profile
      # - OIDC_ADMIN_ROLES=admin
      # - OIDC_ROLES_ATTRIBUTE=groups
      # - OIDC_IGNORE_ROLES=true

volumes:
  user-avatars:
  project-background-images:
  attachments:
